### ISSUE TITLE
E38 Support: Error parsing Navigation data

### ISSUE THREAD

**Issue by tedsalmon** [t3ddftw/DroidIBus#47]
```
07-20 23:53:59.406 D/DroidIBus(2613): Received Message (NavigationEurope -> Telephone): 7F 14 C8 A2 00 00 38 48 30 00 00 77 09 24 71 00 00 00 00 04 00 6E 
07-20 23:53:59.407 W/System.err(2613):  at net.littlebigisland.droidibus.ibus.systems.NavigationSystemCommand$Telephone.mapReceived(NavigationSystemCommand.java:112)
07-20 23:53:59.407 W/System.err(2613):  at net.littlebigisland.droidibus.ibus.IBusSystemCommand.mapReceived(IBusSystemCommand.java:128)
07-20 23:53:59.407 W/System.err(2613):  at net.littlebigisland.droidibus.ibus.IBusMessageService$1.handleMessage(IBusMessageService.java:265)
07-20 23:53:59.407 W/System.err(2613):  at net.littlebigisland.droidibus.ibus.IBusMessageService$1.loop(IBusMessageService.java:184)
07-20 23:53:59.407 W/System.err(2613):  at net.littlebigisland.droidibus.ibus.systems.NavigationSystemCommand$Telephone.parseGPSData(NavigationSystemCommand.java:44)
07-20 23:53:59.423 D/DroidIBus(2613): Received Message (Radio -> DigitalSignalProcessingAudioAmplifier): 68 04 6A 32 31 05 
```

**Comment by tedsalmon** [comment]
FIxed in pull request #52
