### ISSUE TITLE
Invalid calls to getLinkState on a null object causing force quits

### ISSUE THREAD

**Issue by tedsalmon** [t3ddftw/DroidIBus#54]
```
07-23 19:23:50.285 E/AndroidRuntime(3857): Process: net.littlebigisland.droidibus, PID: 3857
07-23 19:23:50.285 E/AndroidRuntime(3857): java.lang.RuntimeException: Unable to start activity ComponentInfo{net.littlebigisland.droidibus/net.littlebigisland.droidibus.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.littlebigisland.droidibus.ibus.IBusMessageService.getLinkState()' on a null object reference
07-23 19:23:50.285 E/AndroidRuntime(3857):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at android.app.ActivityThread.access$800(ActivityThread.java:144)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at android.os.Handler.dispatchMessage(Handler.java:102)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at android.os.Looper.loop(Looper.java:135)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at android.app.ActivityThread.main(ActivityThread.java:5221)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at java.lang.reflect.Method.invoke(Native Method)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at java.lang.reflect.Method.invoke(Method.java:372)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
07-23 19:23:50.285 E/AndroidRuntime(3857):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by tedsalmon** [comment]
Fixed in #57
