### ISSUE TITLE
Force Close: ConcurrentModificationException in Music service

### ISSUE THREAD

**Issue by tedsalmon** [t3ddftw/DroidIBus#55]
```
07-23 19:23:17.056 E/AndroidRuntime(4314): Process: net.littlebigisland.droidibus, PID: 4314
07-23 19:23:17.056 E/AndroidRuntime(4314): java.util.ConcurrentModificationException
07-23 19:23:17.056 E/AndroidRuntime(4314):  at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at java.util.HashMap$KeyIterator.next(HashMap.java:814)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at net.littlebigisland.droidibus.music.MusicControllerService.setMediaControllers(MusicControllerService.java:282)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at net.littlebigisland.droidibus.music.MusicControllerService.onActiveSessionsChanged(MusicControllerService.java:333)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at android.media.session.MediaSessionManager$SessionsChangedWrapper$1$1.run(MediaSessionManager.java:343)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at android.os.Handler.handleCallback(Handler.java:739)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at android.os.Handler.dispatchMessage(Handler.java:95)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at android.os.Looper.loop(Looper.java:135)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at android.app.ActivityThread.main(ActivityThread.java:5221)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at java.lang.reflect.Method.invoke(Native Method)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at java.lang.reflect.Method.invoke(Method.java:372)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
07-23 19:23:17.056 E/AndroidRuntime(4314):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by tedsalmon** [comment]
Fixed in #58
