### ISSUE TITLE
Fix force close associated with playbackState call

### ISSUE THREAD

**Issue by tedsalmon** [t3ddftw/DroidIBus#61]
```
07-27 10:49:09.474 E/AndroidRuntime(4406): FATAL EXCEPTION: main
07-27 10:49:09.474 E/AndroidRuntime(4406): Process: net.littlebigisland.droidibus, PID: 4406
07-27 10:49:09.474 E/AndroidRuntime(4406): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.session.PlaybackState.getState()' on a null object reference
07-27 10:49:09.474 E/AndroidRuntime(4406):  at net.littlebigisland.droidibus.activity.DashboardMusicFragment$2.onServiceConnected(DashboardMusicFragment.java:164)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1203)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1220)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at android.os.Handler.handleCallback(Handler.java:739)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at android.os.Handler.dispatchMessage(Handler.java:95)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at android.os.Looper.loop(Looper.java:135)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at android.app.ActivityThread.main(ActivityThread.java:5221)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at java.lang.reflect.Method.invoke(Native Method)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at java.lang.reflect.Method.invoke(Method.java:372)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
07-27 10:49:09.474 E/AndroidRuntime(4406):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
07-27 10:49:09.476 W/ActivityManager(531):   Force finishing activity net.littlebigisland.droidibus/.activity.MainActivity
```

**Comment by tedsalmon** [comment]
Fixed in latest version
